/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deneytakipsistemi;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Hamza
 */


public class Add_new_experment extends javax.swing.JFrame {
        
    student_Profil sp;
    public String id;
    /**
     * Creates new form Add_new_experment
     *
     * @param <error>
     */
    
    String path=null;
    String fileName;
     
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement ps = null;

    public Add_new_experment() {
        initComponents();
        con=myConnection.myCon();
        setIconImage();
        
        
        
        
        try {
            String quary = "SELECT DISTINCT NAME FROM EXPERIMENTS";
            ps=con.prepareStatement(quary);
            rs=ps.executeQuery();
            while(rs.next()){
                String name = rs.getString("NAME");
                exNamecombo.addItem(name);
            
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        
        

    }
    public Add_new_experment(String id){
        this.id= id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        myidlbl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        commetnArea = new javax.swing.JTextArea();
        exNamecombo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        testtxt = new javax.swing.JTextField();
        filepathtxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADD NEW  EXPERIMENT");
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myidlbl.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        myidlbl.setText("MY ID");
        jPanel1.add(myidlbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 30));

        jButton1.setText("choose file");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 190, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel4.setText("Add Experment file");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 30));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel3.setText("Commernts and conclosion");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        commetnArea.setColumns(20);
        commetnArea.setFont(new java.awt.Font("Monospaced", 2, 20)); // NOI18N
        commetnArea.setRows(5);
        jScrollPane1.setViewportView(commetnArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 530, 260));

        exNamecombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "choose the experiment" }));
        exNamecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exNamecomboActionPerformed(evt);
            }
        });
        jPanel1.add(exNamecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 190, 30));

        jButton2.setText("SEND");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, 110, 40));
        jPanel1.add(testtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 190, -1));
        jPanel1.add(filepathtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 170, 190, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel2.setText("Experment Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, 30));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/istockphoto-512471968-1024x1024.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         JFileChooser file = new JFileChooser();
        file.setDialogTitle("Select Image");
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images","jpg","gif","png");
        file.addChoosableFileFilter(filter);
        int result = file.showOpenDialog(null);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedfile=file.getSelectedFile();
            path=selectedfile.getAbsolutePath();
  
              fileName=path;
              System.out.println(fileName);
              filepathtxt.setText(fileName);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exNamecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exNamecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exNamecomboActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       
        student_Profil st = new student_Profil();
        System.out.println("aaaaaaaaaaaaaaa");
        st.show(true);
       
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
//        frame.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        frame.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       
    }//GEN-LAST:event_formWindowClosed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int int_id = Integer.parseInt(id);
       String comment = commetnArea.getText();
       String exName = (String) exNamecombo.getSelectedItem();
          // String quary = "UPDATE EXPERIMENTS SET COMMENT='comment', STUDENT_ID="+int_id+" WHERE NAME= 'exName'";
        try {
            String quary = "INSERT INTO EXPERIMENTS (NAME,COMMENT,STUDENT_ID) VALUES (?,?,?)";
            ps = con.prepareStatement(quary);
            ps.setString(1, exName);
            ps.setString(2, comment);
            ps.setInt(3, int_id);
            
            ps.executeUpdate();
            
            String quarry2 = "INSERT INTO FILES (FILE,STUDENT_ID, EXP_NAME) VALUES (?,?,?)";
            
            File file = new File(fileName);
            FileInputStream fis = new FileInputStream(file);
                 ps= con.prepareStatement(quarry2);              
                 ps.setBinaryStream(1, fis, file.length());
                 ps.setString(2, id);
                 ps.setString(3, exName);
                 ps.executeUpdate();
                
               
                JOptionPane.showMessageDialog(null, "SENT SUCCESSFULLY");
                
        } catch (HeadlessException | FileNotFoundException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
                
        }
        this.dispose();
        student_Profil sp = new student_Profil();
        sp.setVisible(true);
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_new_experment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_new_experment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_new_experment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_new_experment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_new_experment().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea commetnArea;
    private javax.swing.JComboBox<String> exNamecombo;
    private javax.swing.JTextField filepathtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel myidlbl;
    public javax.swing.JTextField testtxt;
    // End of variables declaration//GEN-END:variables
    private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/Frame_icon.png")));

    }

   
}
