/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deneytakipsistemi;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Hamza
 */
public class Give_grade extends javax.swing.JFrame {

    /**
     * Creates new form Give_grade
     */
    Teacher_main_frame teacherFrame;
    
    Connection con = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    public Give_grade() {
        initComponents();
        setIconImage();
        con = myConnection.myCon();
        int Ename = teacherFrame.students_extable.getSelectedRow();
        System.out.println(Ename);
//        try {
//            String quary = "SELECT * FROM EXPERIMENTS WHERE NAME=?";
//            ps=con.prepareStatement(quary);
//            
//            
//        } catch (Exception e) {
//        } finally {
//            con.close();
//            
//        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        showfilebtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        STUDENT_COMMETN = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        EX_NAMETXT = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        STU_IDTXT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Give Feedback");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel1.setText("Experment Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, 30));

        showfilebtn.setText("show file");
        showfilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showfilebtnActionPerformed(evt);
            }
        });
        getContentPane().add(showfilebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 190, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel4.setText("view file");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, 30));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel3.setText("Commernts and conclosion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        STUDENT_COMMETN.setEditable(false);
        STUDENT_COMMETN.setColumns(20);
        STUDENT_COMMETN.setFont(new java.awt.Font("Monospaced", 2, 20)); // NOI18N
        STUDENT_COMMETN.setRows(5);
        jScrollPane1.setViewportView(STUDENT_COMMETN);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 530, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel2.setText("WRITE FEEDBACK");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        EX_NAMETXT.setEditable(false);
        EX_NAMETXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EX_NAMETXTActionPerformed(evt);
            }
        });
        getContentPane().add(EX_NAMETXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 260, 30));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 510, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel7.setText("ENTER GRADE");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        jTextField2.setFont(new java.awt.Font("Tw Cen MT", 3, 24)); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 70, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Yet R", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(1, 175, 175));
        jButton2.setText("SEND GRAND AND FEEDBACK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 550, 190, 50));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jLabel8.setText("STUDENT ID");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 110, 30));

        STU_IDTXT.setEditable(false);
        STU_IDTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STU_IDTXTActionPerformed(evt);
            }
        });
        getContentPane().add(STU_IDTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 260, 30));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/istockphoto-512471968-1024x1024.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showfilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showfilebtnActionPerformed
       show_file showf = new show_file();
       showf.setVisible(true);
       this.show(false);
       
        
    }//GEN-LAST:event_showfilebtnActionPerformed

    private void EX_NAMETXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EX_NAMETXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EX_NAMETXTActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Teacher_main_frame Tm= new Teacher_main_frame();
        Tm.show(true);
    }//GEN-LAST:event_formWindowClosing

    private void STU_IDTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STU_IDTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STU_IDTXTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Give_grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Give_grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Give_grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Give_grade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Give_grade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EX_NAMETXT;
    private javax.swing.JTextArea STUDENT_COMMETN;
    private javax.swing.JTextField STU_IDTXT;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton showfilebtn;
    // End of variables declaration//GEN-END:variables
    private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/Frame_icon.png")));
        

        
    }
}
