/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deneytakipsistemi;


import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.ImageIcon;


import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Hamza
 */
public class StudentLogin extends javax.swing.JFrame {
    
    public String id;
     public String pass;
    
//     public StudentLogin(String id) {
//        initComponents();
//     }
//
//    public String getId() {
//        return id;
//    }
    Connection con = null;
    ResultSet rs = null; 
    PreparedStatement ps = null;
    

    /**
     * Creates new form StudentLogin
     */
    public StudentLogin() {
        initComponents();
        con =  myConnection.myCon();
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentIDtxt = new javax.swing.JTextField();
        passtxt = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JLabel();
        backbtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("STUDENT  LOGIN");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentIDtxt.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 18)); // NOI18N
        studentIDtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        studentIDtxt.setBorder(null);
        getContentPane().add(studentIDtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 280, 40));

        passtxt.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 20)); // NOI18N
        passtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passtxt.setBorder(null);
        passtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passtxtActionPerformed(evt);
            }
        });
        getContentPane().add(passtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 280, 40));

        loginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/button_default.png"))); // NOI18N
        loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbtnMouseExited(evt);
            }
        });
        getContentPane().add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 330, 70));

        backbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/back-button.png"))); // NOI18N
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backbtnMouseExited(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sign up");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 450, 70, -1));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Don't have an accoun?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hamza\\Downloads\\student login.png")); // NOI18N
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void passtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passtxtActionPerformed

    private void loginbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseEntered
         loginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/button_hover.png")));
          
                
        
    }//GEN-LAST:event_loginbtnMouseEntered

    private void loginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseClicked
           id=  studentIDtxt.getText();
           pass= passtxt.getText();
          
          try {
            String quary = "SELECT * FROM STUDENTS WHERE ID=? AND PASSWORD=?";
            ps =con.prepareStatement(quary);
            ps.setString(1, id);
            ps.setString(2, pass);
            rs=ps.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Login Succeed");
           
                student_Profil SP = new student_Profil();
                SP.setVisible(true);
                this.dispose();
                
                SP.namelbl.setText(rs.getString("NSURNAME").toUpperCase());
                SP.txt1.setText(rs.getString("NSURNAME"));
                SP.txt2.setText(rs.getString("ID"));
                SP.txt3.setText(rs.getString("EMAIL"));
                SP.txt4.setText(rs.getString("PHONE"));
                SP.comboYear.setSelectedItem(rs.getString("SINIF"));
                if(rs.getString("GENDER").equals("Male")){
                SP.maleR.setSelected(true);
                }else{
                SP.femaleR.setSelected(true);}
                
                
                
                
            }else{
                JOptionPane.showMessageDialog(null, "ID or password are incorrect");
            }
        } catch (SQLException ex) {
              JOptionPane.showMessageDialog(null, ex);
        }
          
          
          
          
          
          
          
    }//GEN-LAST:event_loginbtnMouseClicked

    private void loginbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseExited
         loginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/button_default.png")));
    }//GEN-LAST:event_loginbtnMouseExited

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        this.dispose();
        login li = new login();
        li.setVisible(true);
    }//GEN-LAST:event_backbtnMouseClicked

    private void backbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseEntered
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/back-button-hover.png")));
    }//GEN-LAST:event_backbtnMouseEntered

    private void backbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseExited
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/back-button.png")));
    }//GEN-LAST:event_backbtnMouseExited

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
        jLabel1.setForeground(Color.GREEN);
    }//GEN-LAST:event_jLabel1MouseEntered

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited
        // TODO add your handling code here:
         jLabel1.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel1MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.show(false);
//        SignUp sU = new SignUp();
//        sU.setVisible(true);
        SignUp sU = new SignUp();
        sU.show(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//        SignUp sU = new SignUp();
//        sU.show(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel loginbtn;
    private javax.swing.JPasswordField passtxt;
    public javax.swing.JTextField studentIDtxt;
    // End of variables declaration//GEN-END:variables
    private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/Frame_icon.png")));
        

        
    }
}
