/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deneytakipsistemi;

import java.awt.Toolkit;
import java.sql.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Hamza
 */
public class Teacher_login extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs = null;
    PreparedStatement ps = null;
    String email;
    String pass;
    
    
    /**
     * Creates new form Teacher_login
     */
    public Teacher_login() {
        initComponents();
        con =  myConnection.myCon();
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        temailtxt = new javax.swing.JTextField();
        tpasstxt = new javax.swing.JPasswordField();
        loginbtn = new javax.swing.JLabel();
        backbtn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TEACHER LOGIN");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        temailtxt.setFont(new java.awt.Font("Yu Gothic UI Semilight", 2, 18)); // NOI18N
        temailtxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        temailtxt.setBorder(null);
        getContentPane().add(temailtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 280, 40));

        tpasstxt.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 20)); // NOI18N
        tpasstxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tpasstxt.setBorder(null);
        getContentPane().add(tpasstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 280, 40));

        loginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/button_default.png"))); // NOI18N
        loginbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginbtnMouseExited(evt);
            }
        });
        getContentPane().add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 330, 70));

        backbtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/back-button.png"))); // NOI18N
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backbtnMouseExited(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 40));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/TEACHERlogin.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 602, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        login lg = new login();
        lg.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void loginbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseEntered
        // TODO add your handling code here:
        loginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/button_hover.png")));
    }//GEN-LAST:event_loginbtnMouseEntered

    private void loginbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseExited
        // TODO add your handling code here:
        loginbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/button_default.png")));
    }//GEN-LAST:event_loginbtnMouseExited

    private void backbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseEntered
       backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/back-button-hover.png")));
    }//GEN-LAST:event_backbtnMouseEntered

    private void backbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseExited
       backbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buttons/back-button.png")));
    }//GEN-LAST:event_backbtnMouseExited

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        this.dispose();
        login li = new login();
        li.setVisible(true);
    }//GEN-LAST:event_backbtnMouseClicked

    private void loginbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbtnMouseClicked
        email= temailtxt.getText();
        pass = tpasstxt.getText();
        
        try {
            String quary = "SELECT * FROM TEACHERS WHERE EMAIL=? AND PASSWORD =?";
            ps = con.prepareStatement(quary);
            ps.setString(1, email);
            ps.setString(2, pass);
            rs=ps.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Loin Succeed");
                this.dispose();
                Teacher_main_frame Tf = new Teacher_main_frame();
                Tf.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "email or password are uncorrect!");
            }
        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(null, ex);
        }
               
           
     
    }//GEN-LAST:event_loginbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Teacher_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Teacher_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Teacher_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Teacher_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Teacher_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backbtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel loginbtn;
    private javax.swing.JTextField temailtxt;
    private javax.swing.JPasswordField tpasstxt;
    // End of variables declaration//GEN-END:variables
private void setIconImage() {
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/icons/Frame_icon.png")));
        

        
    }
}
